# Docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: rpi
    steps:
      - bash: make build && API_TOKEN=$API_TOKEN make run
        env:
          API_TOKEN: $(API_TOKEN)