# Docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: tokyo
    steps:
      - bash: echo "$kek"; echo "${kek}"; echo "$(kek)"
        env:
          kek: $(API_TOKEN)