# Docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: rpi
    steps:
      - bash: whoami
      - bash: make build
      - bash: make run