# Docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: tokyo
    steps:
      - bash: echo $API_TOKEN
        env:
          API_TOKEN: $(API_TOKEN)